name: ðŸš¥ Status Checks
on: push

jobs:
  tests:
    name: ðŸ‘€ Evaluate on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Don't cancel other OS runners if one fails.
      fail-fast: false
      matrix:
        # Put the operating systems you want to run on here.
        os: [ubuntu-latest]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      # Smaller cache size
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    defaults:
      run:
        # Use bash shells on all platforms.
        shell: bash
    steps:
      - uses: actions/checkout@v4
        name: ðŸ§¾ Checkout

      - uses: chickensoft-games/setup-godot@v2
        name: ðŸ¤– Setup Godot
        with:
          # Version must include major, minor, and patch, and be >= 4.0.0
          # Pre-release label is optional.
          version: 4.5.1
          # Use .NET-enabled version of Godot (the default is also true).
          use-dotnet: false
          # Include the Godot Export Templates (the default is false).
          include-templates: false

      - name: ðŸ”¬ Verify Setup
        run: |
          godot --version

      - name: ðŸ¦º Checking scripts
        run: |
          for filename in $(find . -name *.gd); do
            echo $filename
            godot --headless --check-only --script "$filename" || true
          done
